### ISSUE TITLE
Docs: Add a demo page

### ISSUE THREAD

**Issue by geongeorge** [neomusic/react-canvas-txt#1]
Hey, It'd be cool if there were a small demo page where people could fiddle around.
Any way you could spin one up?

**Comment by neomusic** [comment]
Hi @geongeorge 
This is a great idea. I will add this as soon as possible

**Comment by neomusic** [comment]
Hi @geongeorge.
I updated readme file with a link codesandbox containing the demo. 

Check out

**Comment by geongeorge** [comment]
Looks perfect!
