### ISSUE TITLE
Canvas fillStyle

### ISSUE THREAD

**Issue by alienbuild** [neomusic/react-canvas-txt#13]
Is it possible to get the ability to change the text colour please?

**Comment by neomusic** [comment]
Hi @alienbuild. This feature is not available in the [source library](https://github.com/geongeorge/Canvas-Txt). Try opening an issue [here](https://github.com/geongeorge/Canvas-Txt/issues)

**Comment by alienbuild** [comment]
Hey, thanks for the reply. I did check there first originally and it is in their README.md example, but not one of the properties. 

```
//You can also use other methods alongside this
ctx.fillStyle = '#ff0000' //red color text
```


I did try forking and editing the CanvasTxt.js file myself to add the above line but it doesn't seem to take effect.

```
    const ctx = this.ref.current.getContext("2d");
    ctx.fillStyle = 'white'
```
