### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by asadrazashah** [neomusic/react-canvas-txt#2]
after changing font size the text clear outs in top left and top right positions and it is visible on other positions 
code I am using
  updateCanvas = (
    video: any,
    img: any,
    context: any,
    context2: any,
    width: any,
    height: any
  ) => {
    context2.drawImage(video, 0, 0, width, height);
    context2.fillStyle = this.state.textColor;
    canvasTxt.vAlign = this.state.vAlign;
    canvasTxt.align = this.state.align;
    canvasTxt.lineHeight = 20;
    canvasTxt.fontSize = this.state.fontSize;
    // canvasTxt.debug = true;
    canvasTxt.drawText(
      context2,
      this.state.text,
      30,
      30,
      width - 50,
      height - 50
    );
    context2.drawImage(img, this.state.logoX, this.state.logoY);
    let idata = context2.getImageData(0, 0, width, height);
    context.putImageData(idata, 0, 0);
  };

**Comment by neomusic** [comment]
Hi @asadrazashah, could you add an example with the reproduced problem?
You could use (for example) https://codesandbox.io/ 😄 

Thanks
