### ISSUE TITLE
fontWeight and fontStyle problems

### ISSUE THREAD

**Issue by Dadidam** [neomusic/react-canvas-txt#3]
I wasn't able to set `bold` or `italic` to change the text view as I needed.

Tried also at your demo page - seems not working for me there too, so something related to Canvas code I think.

Please advise, how to make my text "bold". Approach using `fontWeight: "bold"` and other doesn't work for me in Chrome, FF, and Edge.

Thanks!

**Comment by neomusic** [comment]
Hi @Dadidam.
Thank you for letting me know. In fact there is a bug 🐛

**Comment by Dadidam** [comment]
@neomusic sounds great! 

Just FYI, I was able to apply bold on a simple Canvas by passing just a string like `bold 16px Roboto`, but it doesn't make a trick with the **react-canvas-text** component.

Anyway, thank you for your help. I'll be waiting for the update!

**Comment by Dadidam** [comment]
Any updates on that @neomusic?

Also noticed, that render method has `console.log(this.props);` which is not good for production usages.

**Comment by neomusic** [comment]
Hi @Dadidam 
Check the latest version `1.1.1`

**Comment by Dadidam** [comment]
@neomusic nice, thank you.

P.S. Still see log message from render().

**Comment by neomusic** [comment]
@Dadidam I checked in my source code and I don't find nothing `console.log` 
Are you sure is in my code?

**Comment by alienbuild** [comment]
This he means line 49 of CanvasTxt.js

**Comment by neomusic** [comment]
@alienbuild please can you link me the file? 😅

**Comment by alienbuild** [comment]
It's not present in github but when you do `yarn add react-canvas-txt` you can find it in `node_modules/react-canvas-txt/dist/CanvasTxt.js` 

Line 49     console.log(this.props) 

which prints out the original object.
